### ISSUE TITLE
已绑定微信的用户扫（管理后台给的码）报错

### ISSUE THREAD

**Issue by caijiang** [mingshz/ShoppingBeauty#33]
2018/02/06 14:56:49 [http-apr-8080-exec-7] m.j.w.w.m.AbstractHandler 67 webAuth - get  web-auth success for code:081AbpA61Dy2TR1woAA6150DA61AbpAf
2018/02/06 14:56:49 [http-apr-8080-exec-7] m.j.w.p.i.h.WeixinResponseHandler 55 handleEntity - [WEIXIN] response:{"errcode":40163,"errmsg":"code been used, hints: [ req_id: o1acHa0209th41 ]"}
2018/02/06 14:56:49 [http-apr-8080-exec-7] m.j.w.p.i.h.WeixinResponseHandler 61 handleEntity - [WEIXIN] unexpected: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "errcode" (class me.jiangcai.wx.model.UserAccessResponse), not marked as ignorable (5 known properties: "expires_in", "scope", "refresh_token", "access_token", "openid"])
 at [Source: [B@5955e6b8; line: 1, column: 17] (through reference chain: me.jiangcai.wx.model.UserAccessResponse["errcode"])

at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51) ~[jackson-databind-2.6.4.jar:2.6.4]
	
	at me.jiangcai.wx.protocol.impl.ProtocolCallback.invoke(ProtocolCallback.java:42) [weixin-protocol-2.2.0-20180206.020555-7.jar:?]
	at me.jiangcai.wx.protocol.Protocol$$EnhancerByCGLIB$$e5990cf0.userToken(<generated>) [weixin-protocol-2.2.0-20180206.020555-7.jar:?]
	at me.jiangcai.wx.web.mvc.AbstractHandler.webAuth(AbstractHandler.java:68) [weixin-web-2.2.0-20180206.020611-7.jar:?]
	at me.jiangcai.wx.web.mvc.WeixinUserDetailResolver.resolveArgument(WeixinUserDetailResolver.java:24) [weixin-web-2.2.0-20180206.020611-7.jar:?]

访问URL: http://front.staging.sb.lmjia.cn/managerLogin/2

**Comment by caijiang** [comment]
扫码的时候前端用户可能已登录，也可能未登录，所以先第一时间判断是否已登录。
* 已登录： 没毛病，继续业务逻辑
* 未登录:  将当前地址打个包，然后302到/auth

这样看起来跟Spring Security的默认行为好像……
